services:
  app:
    build:
      context: .
    container_name: goxcrap
    command: ["/goxcrap", "--prod"]
    ports:
      - "${APP_EXPOSED_PORT}:${APP_INTERNAL_PORT}"
    environment:
      APP_API_PORT: ${APP_INTERNAL_PORT:-3001}
      EMAIL: ${EMAIL}
      PASSWORD: ${PASSWORD}
      USERNAME: ${USERNAME}
      DRIVER_PATH: ${DRIVER_PATH}
      BROWSER_PATH: ${BROWSER_PATH}
      BROKER_CONCURRENT_MESSAGES: ${BROKER_CONCURRENT_MESSAGES}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'curl -sSf http://localhost:${APP_INTERNAL_PORT}/ping/v1 || exit 1'" ]
      interval: 5s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: rabbitmq
    hostname: 'goxcrap'
    ports:
      - "5672:${RABBITMQ_PORT:-5672}"
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms" ]
      start_period: 1m
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:

networks:
  app:
    driver: bridge